Tiendav3/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Tiendav3.Models;

namespace Tiendav3.Controllers
{
    public class ClienteController : Controller
    {
        private readonly crud_meloContext _context;

        public ClienteController(crud_meloContext context)
        {
            _context = context;
        }

        // GET: Cliente
        public async Task<IActionResult> Index(string searchCedula)

        {
			var clientes = from c in _context.Clientes
						   select c;

			if (!string.IsNullOrEmpty(searchCedula))
			{
				clientes = clientes.Where(c => c.Cedula.ToString().Contains(searchCedula));
			}

			return View(await clientes.ToListAsync());
			//return _context.Clientes != null ? 
   //                       View(await _context.Clientes.ToListAsync()) :
   //                       Problem("Entity set 'crud_meloContext.Clientes'  is null.");

        }
        // GET: Clientes

        // GET: Cliente/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cliente/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Cedula,Nombre,Direccion,Telefono")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Cliente/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: Cliente/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Cedula,Nombre,Direccion,Telefono")] Cliente cliente)
        {
            if (id != cliente.Cedula)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.Cedula))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Cliente/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.Cedula == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Cliente/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Clientes == null)
            {
                return Problem("Entity set 'crud_meloContext.Clientes' is null.");
            }

            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente != null)
            {
                var facturas = await _context.Facturas.Where(f => f.ClienteCedula == id).ToListAsync();
                _context.Facturas.RemoveRange(facturas);

                _context.Clientes.Remove(cliente);
            }
            else
            {
                return NotFound();
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(int id)
        {
          return (_context.Clientes?.Any(e => e.Cedula == id)).GetValueOrDefault();
        }
    }
}

Tiendav3/Controllers/FacturaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Tiendav3.Models;

namespace Tiendav3.Controllers
{
    public class FacturaController : Controller
    {
        private readonly crud_meloContext _context;

        public FacturaController(crud_meloContext context)
        {
            _context = context;
        }

        // GET: Factura
        public async Task<IActionResult> Index(string searchFactura)
        {
            var facturas = from c in _context.Facturas
                            select c;
            var crud_meloContext = _context.Facturas.Include(f => f.ClienteCedulaNavigation).Include(f => f.ProductoCodigoNavigation);
            if (!string.IsNullOrEmpty(searchFactura))
            {
                facturas = facturas.Where(c => c.NumeroFactura.ToString().Contains(searchFactura));
            }
            View(await crud_meloContext.ToListAsync());
            return View(await facturas.ToListAsync()); 

            
            //return View(await crud_meloContext.ToListAsync());
        }

        // GET: Factura/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Facturas == null)
            {
                return NotFound();
            }

            var factura = await _context.Facturas
                .Include(f => f.ClienteCedulaNavigation)
                .Include(f => f.ProductoCodigoNavigation)
                .FirstOrDefaultAsync(m => m.NumeroFactura == id);
            if (factura == null)
            {
                return NotFound();
            }

            return View(factura);
        }

        // GET: Factura/Create
        public IActionResult Create()
        {
            ViewData["ClienteCedula"] = new SelectList(_context.Clientes, "Cedula", "Cedula");
            ViewData["ProductoCodigo"] = new SelectList(_context.Productos, "Codigo", "Codigo");
            return View();
        }

        // POST: Factura/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NumeroFactura,ClienteCedula,ValorTotal,Fecha,ProductoCodigo,Cantidad,Valor")] Factura factura)
        {
            if (ModelState.IsValid)
            {
                var producto = await _context.Productos.FindAsync(factura.ProductoCodigo);
                if (producto == null)
                {
                    return NotFound();
                }
                bool numeroFacturaRepetido = await _context.Facturas.AnyAsync(f => f.NumeroFactura == factura.NumeroFactura);
                if (numeroFacturaRepetido)
                {
                    ModelState.AddModelError("NumeroFactura", "Ya se encuentra registrado");
                    ViewData["ClienteCedula"] = new SelectList(_context.Clientes, "Cedula", "Cedula", factura.ClienteCedula);
                    ViewData["ProductoCodigo"] = new SelectList(_context.Productos, "Codigo", "Codigo", factura.ProductoCodigo);
                    return View(factura);
                }
                if (factura.Cantidad > producto.Cantidad)
                {
                    ModelState.AddModelError("Cantidad", "La cantidad de productos no es válida.");
                    ViewData["ClienteCedula"] = new SelectList(_context.Clientes, "Cedula", "Cedula", factura.ClienteCedula);
                    ViewData["ProductoCodigo"] = new SelectList(_context.Productos, "Codigo", "Codigo", factura.ProductoCodigo);
                    return View(factura);
                }
                producto.Cantidad = factura.Cantidad;
                producto.CalcularValorTotal();

                factura.Valor = producto.Precio;

                factura.ValorTotal = factura.Cantidad * factura.Valor;
                factura.Cantidad-=producto.Cantidad;

                _context.Add(factura);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteCedula"] = new SelectList(_context.Clientes, "Cedula", "Cedula", factura.ClienteCedula);
            ViewData["ProductoCodigo"] = new SelectList(_context.Productos, "Codigo", "Codigo", factura.ProductoCodigo);
            return View(factura);
        }

        // GET: Factura/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Facturas == null)
            {
                return NotFound();
            }

            var factura = await _context.Facturas.FindAsync(id);
            if (factura == null)
            {
                return NotFound();
            }

            ViewData["ClienteCedula"] = new SelectList(_context.Clientes, "Cedula", "Cedula", factura.ClienteCedula);
            ViewData["ProductoCodigo"] = new SelectList(_context.Productos, "Codigo", "Codigo", factura.ProductoCodigo);
            return View(factura);
        }

        // POST: Factura/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NumeroFactura,ClienteCedula,ValorTotal,Fecha,ProductoCodigo,Cantidad,Valor")] Factura factura)
        {
            if (id != factura.NumeroFactura)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var producto = await _context.Productos.FindAsync(factura.ProductoCodigo);
                if (producto == null)
                {
                    return NotFound();
                }

                if (factura.Cantidad > producto.Cantidad)
                {
                    ModelState.AddModelError("Cantidad", "La cantidad de productos no es válida.");
                    ViewData["ClienteCedula"] = new SelectList(_context.Clientes, "Cedula", "Cedula", factura.ClienteCedula);
                    ViewData["ProductoCodigo"] = new SelectList(_context.Productos, "Codigo", "Codigo", factura.ProductoCodigo);
                    return View(factura);
                }
                producto.Cantidad = factura.Cantidad;
                producto.CalcularValorTotal();

                factura.Valor = producto.Precio;

                factura.ValorTotal = factura.Cantidad * factura.Valor;
                factura.Cantidad -= producto.Cantidad;
                try
                {
                    _context.Update(factura);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FacturaExists(factura.NumeroFactura))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteCedula"] = new SelectList(_context.Clientes, "Cedula", "Cedula", factura.ClienteCedula);
            ViewData["ProductoCodigo"] = new SelectList(_context.Productos, "Codigo", "Codigo", factura.ProductoCodigo);
            return View(factura);
        }

        // GET: Factura/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Facturas == null)
            {
                return NotFound();
            }

            var factura = await _context.Facturas
                .Include(f => f.ClienteCedulaNavigation)
                .Include(f => f.ProductoCodigoNavigation)
                .FirstOrDefaultAsync(m => m.NumeroFactura == id);
            if (factura == null)
            {
                return NotFound();
            }

            return View(factura);
        }

        // POST: Factura/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Facturas == null)
            {
                return Problem("Entity set 'crud_meloContext.Facturas'  is null.");
            }
            var factura = await _context.Facturas.FindAsync(id);
            if (factura != null)
            {
                _context.Facturas.Remove(factura);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Reporte()
        {
            var facturas = await _context.Facturas
                .Include(f => f.ClienteCedulaNavigation)
                .Include(f => f.ProductoCodigoNavigation)
                .ToListAsync();

            var clientes = await _context.Clientes.ToListAsync();
            var productos = await _context.Productos.ToListAsync();

            ViewBag.Clientes = clientes;
            ViewBag.Productos = productos;

            return View(facturas);
        }

        private bool FacturaExists(int id)
        {
          return (_context.Facturas?.Any(e => e.NumeroFactura == id)).GetValueOrDefault();
        }
    }
}

Tiendav3/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Tiendav3.Models;

namespace Tiendav3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Tiendav3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>


    <body>
     @if (User.Identity.IsAuthenticated == false)
    {
        <h1>Bienvenido a la tienda Registrate o Inicia Sesion</h1>
    }
    
    @if (User.Identity.IsAuthenticated)
    {
        <div class="text-center">
            <h1 class="display-4" style="text-shadow: 2px 2px 4px; color:black; font-weight: bold;">Bienvenido a la tienda </h1>
        </div>

        <script>
            var titulo = document.getElementById("titulo");
            var colors = ["blue", "green", "purple", "black"]; // Colores para cambiar

            var index = 0;
            setInterval(function () {
            titulo.style.color = colors[index];
            index = (index + 1) % colors.length;
            }, 2000); // Cambiar cada 2 segundos (2000 milisegundos)
        </script>

        <div class="container text-align: center;" style="display: flex; justify-content: center; align-items: center; height: 50vh; margin: 0;">
            <div class="row">
                <div class="col-md-3">
                    <div class="image-container">
                        <img src="https://www.processmaker.com/wp-content/uploads/2020/09/customer-onboarding.jpg" alt="Imagen 1" class="img-fluid" style="width: 100%; height: 100%;">
                    </div>
                    <a class="btn btn-primary btn-block custom-btn" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                </div>
                <div class="col-md-3">
                    <div class="image-container">
                        <img src="https://www.microtech.es/hubfs/Fotos%20blog/stock_fabrica.jpg" alt="Imagen 2" class="img-fluid" style="width: 100%; height: 100%;">
                    </div>
                    <a class="btn btn-primary btn-block custom-btn" asp-area="" asp-controller="Producto" asp-action="Index">Productos</a>
                </div>
                <div class="col-md-3">
                    <div class="image-container">
                        <img src="https://conceptodefinicion.de/wp-content/uploads/2014/02/Venta-2.jpg" alt="Imagen 3" class="img-fluid" style="width: 100%; height: 100%;">
                    </div>
                    <a class="btn btn-primary btn-block custom-btn" asp-area="" asp-controller="Factura" asp-action="Index">Ventas</a>
                </div>
                <div class="col-md-3">
                    <div class="image-container">
                        <img src="https://www.esic.edu/sites/default/files/rethink/ff01cba7-marketing-y-ventas-roi.jpg" alt="Imagen 4" class="img-fluid" style="width: 100%; height: 100%; border-radius:10px;">
                    </div>
                    <a class="btn btn-primary btn-block custom-btn" asp-area="" asp-controller="Factura" asp-action="Reporte">Reportes</a>
                </div>
            </div>
        </div>

        <style>

        </style>


        <style>
            .custom-btn {
            background-color: #007bff; /* Color de fondo */
            color: white; /* Color de texto */
            border-radius: 10px; /* Borde redondeado */
            padding: 10px 20px; /* Espaciado interno */
            font-size: 18px; /* Tamaño de fuente */
            transition: background-color 0.3s, color 0.3s, transform 0.3s; /* Transición de color y transformación */
            }

            .custom-btn:hover {
            background-color: #0056b3; /* Color de fondo al pasar el mouse */
            color: white; /* Color de texto al pasar el mouse */
            transform: scale(1.1); /* Escala al pasar el mouse */
            }

            .custom-img {
            object-fit: cover;
            }

            .image-container {
            height: 200px; /* Establece una altura fija para el contenedor de la imagen */
            }
        </style>



    }
</body>